Feature/rate limits
COMP-SE-610-620-A2024/device-register pull request #216
Opened 2024-11-16 16:38 UTC by Khalessia

2024-11-16 16:46 UTC, Khalessia commented
@Hilawii Jätin tuonne "poiskommentoituna" mahdollisuuden käyttää limiterissä exempt_when=it_is_admin. Sen sijaan nykyisessä toteutuksessa rate limiterin admin check hoidettu app.py kautta pelkästään apufunktion avulla, jolloin se on vain yhdessä paikassa.

2024-11-17 02:21 UTC, Hilawii requested changes

2024-11-17 02:21 UTC, Hilawii commented on backend/utils/check_admin.py
> +        return False
Voisi olla helpompaa siirtää osa is_admin toteutus tänne ja sitten vaan callata tätä functionta is_adminissa.

2024-11-17 02:23 UTC, Hilawii commented
> @Hilawii Jätin tuonne "poiskommentoituna" mahdollisuuden käyttää limiterissä exempt_when=it_is_admin. Sen sijaan nykyisessä toteutuksessa rate limiterin admin check hoidettu app.py kautta pelkästään apufunktion avulla, jolloin se on vain yhdessä paikassa.

Näyttää fiksummalta ratkaisulta kuin oma alkuperänen ajatus. Hyvin näytti ainakin toimivan mitä kokeilin. Voit poistaa kommentoidut kerran löysit paremman ratkaisun 👍

2024-11-17 04:56 UTC, Khalessia commented on backend/utils/check_admin.py
> +        return False
Refaktoroitu

2024-11-17 09:41 UTC, Hilawii approved these changes

2024-11-17 10:02 UTC, Hilawii requested changes
Lisääppä swaggeriin vielä noihin joissa optional token niin optional authorzaton parametri


      parameters:
        - in: header
          name: Authorization
          description: Optional JWT token (Bearer format)
          required: false
          type: string

2024-11-17 15:59 UTC, Hilawii approved these changes

2024-11-17 16:00 UTC, merged